# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32d72a0e50ad28fbfaa821c638a8522f0ffa810ae9c2d95b099c1efed9bc7f764c1b34c024aabe071df0ef90ffa09b09bd2acef22f8b6067e10da9f09c2eed4d

test:
  secret_key_base: 6a939a612979c6fe86614f003fe842566a3d39cf15d4b5ce7a85cdec4aa33013d40aadc96109a57d6e46d253bfd81292f645fd7062d650982a1b4074d826f854

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
